#+title: Sent
#+author: Lucien “Phundrak” Cartier-Tilet

* Presentation
  =sent= is a simple plaintext presentation tool.

  =sent= does  not need LaTeX,  LibreOffice or any  other fancy file  format, it
  uses  plaintext files  to  describe  the slides  and  can  include images  via
  =farbfeld=. Every paragraph represents a slide in the presentation.

  The presentation  is displayed  in a  simple X11 window.  The content  of each
  slide is automatically scaled to fit the window and centered so you also don't
  have  to worry  about alignment.  Instead you  can really  concentrate on  the
  content.

* Dependencies

  You need Xlib and Xft to build  sent and the farbfeld[fn:1] tools installed to
  use images in your presentations.

* Build
  =sent=  is  built with  the  Meson  and Ninja  build  system.  Simply run  the
  following:
  #+BEGIN_SRC sh
  meson build && ninja -C build/
  #+END_SRC
  =sent= will be compiled and available  in =build/sent=. If you wish to install
  =sent=, simply run
  #+BEGIN_SRC sh
  ninja -C build/ install
  #+END_SRC
  You  may need  to execute  the  above command  as sudo.  To uninstall  =sent=,
  execute
  #+BEGIN_SRC sh
  ninja -C build/ uninstall
  #+END_SRC

* Demo
  To get a little demo, just type
  #+BEGIN_SRC sh
  ./build/sent example
  #+END_SRC

* Usage
  #+BEGIN_SRC sh
  sent [FILE]
  #+END_SRC

  If FILE is omitted or equals =-=,  stdin will be read. Produce image slides by
  prepending  a ~@~  in  front of  the  filename as  a  single paragraph.  Lines
  starting with ~#~ will be ignored. A  ~\~ at the beginning of the line escapes
  ~@~ and ~#~. A presentation file could look like this:
  #+BEGIN_SRC text
    sent

    @nyan.png

    depends on
    - Xlib
    - Xft
    - farbfeld

    sent FILENAME
    one slide per paragraph
    # This is a comment and will not be part of the presentation
    \# This and the next line start with backslashes

    \@FILE.png

    thanks / questions?
  #+END_SRC

* Development

  =sent= is developed at [[http://tools.suckless.org/sent][http://tools.suckless.org/sent]] and here.

* Footnotes

[fn:1] [[http://tools.suckless.org/farbfeld/][http://tools.suckless.org/farbfeld/]]
